### PR TITLE
Add basic CLI

### LINKED ISSUE #36: Add a basic CLI
There have been some requests for a simple CLI for use cases where you aren't using another build tool:

- https://twitter.com/chriscoyier/status/1481350761183420421
- https://twitter.com/WickyNilliams/status/1481378796439752707
- https://twitter.com/Benoit_Chantre/status/1481374449819697152

We could build something super simple using Rust. I think just adding a `main.rs` should be enough to get a binary target.

### PR DESCRIPTION
**Pull request by schultyy**
This PR ships with a basic implementation of a CLI for parcel-css using clap-rs.

Resolves #36

### CODE REVIEW

**Comment by devongovett** [comment]
Hey, thanks for starting this! I'll try it out tomorrow. 😄

**Comment by joelmoss** [comment]
Would be awesome if the CLI could (optionally) return the output to stdout instead of writing to a file :)

**Comment by schultyy** [comment]
Done!

**Review by devongovett — APPROVED** [review]
Thanks! Nice work. Looks like it will be pretty easy to add more features on top of it too!

**Comment by schultyy** [comment]
Yay! Thanks! Happy I could contribute!

**Comment by joelmoss** [comment]
Apologies for my lack of Rust knowledge, but how would I actually use this CLI?

**Comment by devongovett** [comment]
We still need to figure out a nicer distribution method once we have a few more features (#52), but for now you can install with cargo:

```
cargo install parcel_css --version1.0.0-alpha.12
```

And that gives you a global `parcel_css` binary.

**Comment by joelmoss** [comment]
Is the resulting binary platform dependent? As in, it is compiled for the platform/OS you run that command on?

**Comment by rrcobb** [comment]
> Is the resulting binary platform dependent? As in, it is compiled for the platform/OS you run that command on?

It should be platform independent, so long as you have the appropriate local rust setup, via `rustup`! If you `cargo install` something, it should always be fit to your platform. See more on [the install command's page in the The Cargo Book](https://doc.rust-lang.org/cargo/commands/cargo-install.html).

**Comment by mischnic** [comment]
> As in, it is compiled for the platform/OS you run that command on?

It is compiled on the machine you run the command on. So in that sense:

> Is the resulting binary platform dependent

no. But it will run on your machine

**Pull request merged**
