### PR TITLE
fix: add libc fields only to platforms that have libc

### PR DESCRIPTION
**Pull request by yisibl**
Add the libc field in a clearer and more explicit way.
After this PR, `linux-gnueabihf` also no longer adds the `libc` field.
### Before

```json
{
  "name": "@parcel/css-linux-arm-gnueabihf",
  "libc": [
    "gnueabihf"
  ]
}
```

Related PRs: https://github.com/parcel-bundler/parcel-css/pull/205, https://github.com/parcel-bundler/parcel-css/pull/208

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
@yisibl the libc field on `linux-arm-gnueabihf` should be `glibc`.

**Comment by Brooooooklyn** [comment]
@yisibl the libc field on `linux-arm-gnueabihf` should be `glibc`.

**Comment by yisibl** [comment]
@Brooooooklyn Thanks! It looks like the [napi-rs template](https://github.com/napi-rs/package-template/blob/0e2b015e97aa8b9aac9cdad5b8e2e375273f0981/npm/linux-arm-gnueabihf/package.json#L4-L9) needs to be updated as well?

**Comment by Brooooooklyn** [comment]
@yisibl I don't think the `libc` field in `linux-arm-gnueabihf` is necessary, since there is only `glibc` runtime for `linux-arm`.

**Comment by yisibl** [comment]
@devongovett PTAL, thanks!

**Review by devongovett — APPROVED** [review]

**Pull request merged**
