### PR TITLE
Add csso to benchmark

### PR DESCRIPTION
**Pull request by mischnic**
I also tried to find the css files you used for the benchmark in the readme, but the ones in the npm packages (I listed them in the comment) don't seem to be it?

### CODE REVIEW

**Comment by devongovett** [comment]
I was using the files in https://github.com/GoalSmashers/css-minification-benchmark. Not sure if we need to duplicate that whole benchmark here. Hopefully https://github.com/GoalSmashers/css-minification-benchmark/pull/101 will get merged.

**Comment by devongovett** [comment]
Also I'm pretty sure csso does unsafe transforms by default (unless the `restructure` option is turned off). i.e. it merges non-adjacent selectors... 😬

**Comment by mischnic** [comment]
Wow, from their readme 

> `restructure`: Disable or enable a structure optimisations.
> 
> `forceMediaMerge`: ... The optimisation is unsafe in general, but should work fine in most cases. Use it on your own risk.

I got the sense that `restructure` was safe.

**Comment by onigoetz** [comment]
The benchmarks here are now up-to-date : https://goalsmashers.github.io/css-minification-benchmark/

However these don't have specific browser targets, so it's not using advanced optimizations

**Pull request closed without merging**
