### PR TITLE
Add method to lazily compute property source ranges

### LINKED ISSUE #168: How can we get location of each AST node?
From the [Rust doc](https://docs.rs/parcel_css/1.0.0-alpha.24/parcel_css/index.html), it looks that only rules contain a field called `location`, while other AST nodes don't. How can I get location for any type of AST node?

### PR DESCRIPTION
**Pull request by devongovett**
Closes #168

We don't store source locations for every property/value currently, because that would use a lot of additional memory, and it's rare to need source locations except in errors. So this adds a method to lazily compute the source locations of the keys/values of declarations within a style rule. Essentially, it performs a very lightweight additional parsing pass to first find the stored location of the parent style rule, and then finding the declaration by index from there.

This approach is somewhat error prone (e.g. if you modified the style sheet) so I'm not sure if it's a good idea or not. Alternatives would be to store source locations for everything, which I'd prefer not to do if we can help it, or somehow optionally store them externally (but I'm not sure how).

### CODE REVIEW

**Comment by g-plane** [comment]
> somehow optionally store them externally

Is it possible that providing something like hooks when parsing then let downstream developers to do something else, such as storing source locations?

**Comment by devongovett** [comment]
Yeah possible, but how would you look them up? Making the nodes hashable or something wouldn't be enough because two nodes could be equal in different parts of the tree, but have different locations. We'd need to store at least some identifier in each node I guess.

**Comment by g-plane** [comment]
I see. Is it possible that calculating source locations for specific type of node in downstream code? For example, just for functions or colors.

**Review by g-plane — APPROVED** [review]

**Comment by devongovett** [comment]
Going to merge this for now. Will continue to think about ways to get more granular information in the future.

**Pull request merged**
